publish:
  image: python
  script:
    - python setup.py sdist bdist_wheel
    - pip install twine
    - twine upload
        --repository-url ${NEXUS_URL}repository/pypi-hosted/
        --username ${NEXUS_USER}
        --password ${NEXUS_PWD}
        dist/*